import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { toast } from "sonner";
import { api, getSession } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { RequireAuth } from "@/components/require-auth";
export const Route = createFileRoute("/shuttle-driver")({ component: () => <RequireAuth><DriverPage /></RequireAuth> });
function DriverPage() { const userId = getSession()?.user?.userId; const [form, setForm] = useState({ phone: "", vehicleName: "", vehicleNumber: "", profileInfo: "" }); const [route, setRoute] = useState("Kuril"); const apply = (e) => { e.preventDefault(); if (!userId) return toast.error("Please sign in first."); api("/api/shuttle/drivers", { method: "POST", body: JSON.stringify({ userId, ...form }) }).then(() => toast.success("Driver application submitted.")).catch((e) => toast.error(e.message)); }; const start = () => { if (!userId) return toast.error("Please sign in first."); api("/api/shuttle/trips", { method: "POST", body: JSON.stringify({ driverId: userId, route, startNow: true }) }).then(() => toast.success("Trip created.")).catch((e) => toast.error(e.message)); }; return <main className="container-shell max-w-3xl py-10"><h1 className="font-display text-3xl font-bold">Shuttle driver portal</h1><p className="mt-2 text-muted-foreground">Apply as a driver and start approved shuttle trips.</p><div className="mt-8 grid gap-6 md:grid-cols-2"><form className="space-y-4 rounded-xl border p-5" onSubmit={apply}><h2 className="font-semibold">Driver application</h2>{Object.entries({ phone: "Phone", vehicleName: "Vehicle name", vehicleNumber: "Vehicle number", profileInfo: "About you" }).map(([key, label]) => <div key={key}><Label htmlFor={key}>{label}</Label><Input id={key} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></div>)}<Button type="submit">Apply as driver</Button></form><section className="space-y-4 rounded-xl border p-5"><h2 className="font-semibold">Start a trip</h2><Label htmlFor="route">Route</Label><select id="route" className="h-10 w-full rounded-md border border-input bg-background px-3" value={route} onChange={(e) => setRoute(e.target.value)}>{["Kuril", "Notun Bazar", "Aftab-Nagor"].map((r) => <option key={r}>{r}</option>)}</select><Button onClick={start}>Start active trip</Button><p className="text-xs text-muted-foreground">Only approved drivers can start trips.</p></section></div></main>; }
