import { useState } from "react";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { toast } from "sonner";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
export const Route = createFileRoute("/verify-email")({ validateSearch: (search) => ({ email: search.email ?? "" }), component: VerifyEmail });
function VerifyEmail() { const navigate = useNavigate(); const { email: initialEmail } = Route.useSearch(); const [email, setEmail] = useState(initialEmail); const [code, setCode] = useState(""); const [busy, setBusy] = useState(false); const verify = (e) => { e.preventDefault(); setBusy(true); api("/api/users/verify-email", { method: "POST", body: JSON.stringify({ email, code }) }).then(() => { toast.success("Email verified. You can now sign in."); navigate({ to: "/login" }); }).catch((e) => toast.error(e.message)).finally(() => setBusy(false)); }; const resend = () => api("/api/users/resend-verification", { method: "POST", body: JSON.stringify({ email }) }).then(() => toast.success("A new code has been sent.")).catch((e) => toast.error(e.message)); return <main className="container-shell flex min-h-[calc(100vh-4rem)] items-center justify-center py-12"><form className="w-full max-w-md rounded-xl border bg-card p-7 shadow-soft" onSubmit={verify}><h1 className="font-display text-2xl font-bold">Verify your email</h1><p className="mt-2 text-sm text-muted-foreground">Enter the six-digit code sent by Resend. It expires in 10 minutes.</p><div className="mt-6 space-y-4"><div><Label htmlFor="email">Email</Label><Input id="email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></div><div><Label htmlFor="code">Verification code</Label><Input id="code" inputMode="numeric" maxLength={6} value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))} required /></div></div><Button className="mt-6 w-full" disabled={busy}>Verify email</Button><Button type="button" variant="link" className="mt-2 w-full" onClick={resend}>Resend code</Button></form></main>; }
