/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LostAndFoundRouteImport } from './routes/lost-and-found'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MyListingsRouteImport } from './routes/my-listings'
import { Route as ShuttleRouteImport } from './routes/shuttle'
import { Route as ShuttleDriverRouteImport } from './routes/shuttle-driver'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ListingIdRouteImport } from './routes/listing.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
})
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
})
const LostAndFoundRoute = LostAndFoundRouteImport.update({
  id: '/lost-and-found',
  path: '/lost-and-found',
  getParentRoute: () => rootRouteImport,
})
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
})
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => rootRouteImport,
})
const ShuttleRoute = ShuttleRouteImport.update({
  id: '/shuttle',
  path: '/shuttle',
  getParentRoute: () => rootRouteImport,
})
const ShuttleDriverRoute = ShuttleDriverRouteImport.update({
  id: '/shuttle-driver',
  path: '/shuttle-driver',
  getParentRoute: () => rootRouteImport,
})
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
})
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
})
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  EditProfileRoute: EditProfileRoute,
  LoginRoute: LoginRoute,
  LostAndFoundRoute: LostAndFoundRoute,
  MarketplaceRoute: MarketplaceRoute,
  MyListingsRoute: MyListingsRoute,
  ShuttleRoute: ShuttleRoute,
  ShuttleDriverRoute: ShuttleDriverRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ListingIdRoute: ListingIdRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
